"""Comparison for the `text_density` re-run: all 27 of the paper's cities.

Inputs
------
new batch (corrected model, 6 configs/city):
    output/final_stats_27cities.csv     + output/regional_stats_27cities.csv
    -> 26 cities x 6 configs x 10 seeds, plus SAO PAULO x 6 configs x 6 seeds
       = 1596 sims.

submitted batch (the published paper, n=3):
    output/old/final_stats_agglomeration_submitted.csv          (raw, for levels)
    private/overleaf/text_density/data_submitted/{acp,capital,periphery}_deltas.csv  (the published
    delta panels themselves -- used verbatim so the "submitted" column is the
    paper's own numbers, not a re-derivation of them).

The delta panels for the new batch are built with the *same* code path as
`papers/density_housing_inequality/prepare_data.py` (60-month tail window, baseline =
melhorias OFF x interest medium, matched on city+seed, periphery
population-weighted on baseline pop), and the regressions are the same specs
as `papers/density_housing_inequality/regression.py` (OLS + city FE, HC3).

Every table is reported both on the full published city set and on the subset
the new batch covers, so that a change in coverage is never confused with a
change in the model; plus a 3-seed subsample of the new batch, which isolates
"the design changed from n=3" from "the model changed".

Usage:
    python analysis/validation/compare_density_tier2.py
"""
import os
import sys
from pathlib import Path

import numpy as np
import pandas as pd
import statsmodels.formula.api as smf
from scipy import stats as sps

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT))

from analysis.validation.housing_validation import (  # noqa: E402
    TARGETS, EVAL_START, EVAL_END, compute_derived_monthly_indicators,
)

OUT_DIR = ROOT / "analysis" / "validation"
# The submitted-batch panels. They used to live in papers/density_housing_inequality/data/, but that
# directory is now regenerated by prepare_data.py on the CORRECTED batch, which would
# silently turn every "published vs corrected" comparison below into corrected vs
# corrected. The published panels are archived separately and never overwritten.
# The superseded 27-city, 3-seed panels behind the first submission. They are project
# history rather than reproduction material, so they are kept outside the public tree.
# Only main() reads them; regen_tables.py imports this module as a library and does not.
PUB_DIR = Path(os.environ.get(
    "PS3_PUBLISHED_PANELS",
    ROOT / "private" / "overleaf" / "text_density" / "data_submitted"))

# The batch arrived as several launches (the 25-city pack, a separate Rio de Janeiro
# run, and two Sao Paulo runs) and has since been concatenated into one file per level.
# The launch timestamps inside simulation_id survive the concatenation, which is what
# assign_seed() needs: Rio and Sao Paulo both number their replications from 0 in each
# launch, and only the timestamp distinguishes the blocks.
NEW_STATS = [ROOT / "output" / "final_stats_27cities.csv"]
NEW_REG = [ROOT / "output" / "regional_stats_27cities.csv"]
OLD_STATS = ROOT / "output" / "old" / "final_stats_agglomeration_submitted.csv"

MISSING_CITY = None                 # every published city is present in the new batch
COMPLETE_MONTHS = 360
WINDOW_MONTHS = 60
IH_MAP = {"baixa": "low", "media": "medium", "alta": "high"}
BASELINE_IH, BASELINE_PM = "medium", False

ACP_COLS = ["gini_index", "house_price", "affordability_median",
            "house_quality", "house_vacancy", "unemployment", "pop"]
MUN_COLS = ["regional_gini", "regional_house_values", "median_affordability", "pop"]

REG_USECOLS = ["month", "mun_id", "pop", "regional_gini", "regional_house_values",
               "median_affordability", "melhorias_eligible", "melhorias_upgrades",
               "interest_housing", "policy_melhorias", "processing_acps",
               "simulation_id"]

INDICATORS = ["housing_stock_gdp", "price_income", "housing_production_per_1000",
              "consumption_gdp", "vacancy", "housing_stock_permanent_income",
              "gini", "zero_cons", "unemployment"]

# Table 2 of the paper, in its own order, with the empirical ranges it prints.
PAPER_TABLE2 = {
    "housing_stock_gdp": (1.5, 2.5),
    "price_wage": (60, 150),
    "price_income": (6, 12),
    "vacancy": (0.08, 0.13),
    "consumption_gdp": (0.55, 0.65),
    "housing_production_per_1000": (2.0, 4.0),
    "housing_stock_permanent_income": (5.0, 8.0),
}


def stars(p):
    return "***" if p < 0.01 else "**" if p < 0.05 else "*" if p < 0.1 else ""


def assign_seed(df):
    """Give every run a seed index that is unique *and* matched within a city.

    The replication index in `simulation_id` restarts at 0 in every launch, and
    RIO DE JANEIRO was run as two separate `-n 5` launches (2026-08-05 and
    2026-08-07) whose seed-0 runs are demonstrably different draws. Keying on
    the bare index would treat those as one seed and cross-join the two blocks.
    The launch timestamp is therefore part of the key; within a city the
    (timestamp, index) blocks are renumbered 0..k-1 so that `seed < 3` still
    means "the first three replications".
    """
    ts = df["simulation_id"].str.split("__").str[0]
    idx = df["simulation_id"].str.split("__").str[-1].astype(int)
    key = ts + "#" + idx.astype(str)
    order = (pd.DataFrame({"city": df["processing_acps"], "key": key})
             .drop_duplicates().sort_values(["city", "key"]))
    order["seed"] = order.groupby("city").cumcount()
    m = dict(zip(zip(order["city"], order["key"]), order["seed"]))
    return pd.Series(list(map(m.get, zip(df["processing_acps"], key))), index=df.index)


# ---------------------------------------------------------------------------
# Loading
# ---------------------------------------------------------------------------
def load_stats(paths, label):
    df = pd.concat([pd.read_csv(p, low_memory=False) for p in np.atleast_1d(paths)],
                   ignore_index=True)
    df["month"] = pd.to_datetime(df["month"])
    df["interest_housing"] = df["interest_housing"].map(IH_MAP)
    df["seed"] = assign_seed(df)
    df["policy_melhorias"] = df["policy_melhorias"].astype(bool)
    n = df.groupby("simulation_id")["month"].nunique()
    keep = n[n == COMPLETE_MONTHS].index
    if len(keep) < len(n):
        bad = n[n < COMPLETE_MONTHS]
        print(f"  [{label}] dropping {len(bad)} incomplete sims "
              f"({sorted(bad.unique())} months)")
        drop_meta = (df[df["simulation_id"].isin(bad.index)]
                     [["processing_acps", "interest_housing", "policy_melhorias"]]
                     .drop_duplicates())
        print(drop_meta.to_string(index=False))
    df = df[df["simulation_id"].isin(keep)].copy()
    df["run_id"] = df["simulation_id"]
    return df


def load_regional(paths, label):
    frames = []
    for p in np.atleast_1d(paths):
        cols = pd.read_csv(p, nrows=0).columns
        frames.append(pd.read_csv(p, usecols=[c for c in REG_USECOLS if c in cols],
                                  low_memory=False))
    df = pd.concat(frames, ignore_index=True)
    df["month"] = pd.to_datetime(df["month"])
    df["interest_housing"] = df["interest_housing"].map(IH_MAP)
    df["seed"] = assign_seed(df)
    df["policy_melhorias"] = df["policy_melhorias"].astype(bool)
    n = df.groupby("simulation_id")["month"].nunique()
    keep = n[n == COMPLETE_MONTHS].index
    if len(keep) < len(n):
        print(f"  [{label}] dropping {len(n) - len(keep)} incomplete regional sims")
    return df[df["simulation_id"].isin(keep)].copy()


# ---------------------------------------------------------------------------
# Delta panels -- the logic of papers/density_housing_inequality/prepare_data.py
# ---------------------------------------------------------------------------
def build_panels(stats, reg):
    T = stats["month"].max()
    T0 = T - pd.DateOffset(months=WINDOW_MONTHS - 1)
    sw = stats[(stats["month"] >= T0) & (stats["month"] <= T)]
    rw = reg[(reg["month"] >= T0) & (reg["month"] <= T)]

    gacp = ["simulation_id", "processing_acps", "interest_housing",
            "policy_melhorias", "seed"]
    gmun = ["simulation_id", "processing_acps", "mun_id", "interest_housing",
            "policy_melhorias", "seed"]
    sm = sw.groupby(gacp)[ACP_COLS].mean().reset_index()
    rm = rw.groupby(gmun)[MUN_COLS].mean().reset_index()

    base_a = (sm["policy_melhorias"] == BASELINE_PM) & (sm["interest_housing"] == BASELINE_IH)
    base_r = (rm["policy_melhorias"] == BASELINE_PM) & (rm["interest_housing"] == BASELINE_IH)

    ba = (sm[base_a][["processing_acps", "seed"] + ACP_COLS]
          .rename(columns={c: f"{c}_base" for c in ACP_COLS}))
    br = (rm[base_r][["processing_acps", "mun_id", "seed"] + MUN_COLS]
          .rename(columns={c: f"{c}_base" for c in MUN_COLS}))

    acp = sm[~base_a].merge(ba, on=["processing_acps", "seed"], how="inner")
    mun = rm[~base_r].merge(br, on=["processing_acps", "mun_id", "seed"], how="inner")

    for c in ["gini_index", "house_price", "affordability_median",
              "house_quality", "house_vacancy", "unemployment"]:
        acp[f"delta_{c}"] = acp[c] - acp[f"{c}_base"]
    acp = acp.rename(columns={"delta_gini_index": "delta_gini",
                              "delta_house_vacancy": "delta_vacancy"})
    for c in ["regional_gini", "regional_house_values", "median_affordability"]:
        mun[f"delta_{c}"] = mun[c] - mun[f"{c}_base"]

    label = lambda r: f"{r['interest_housing']}_{'active' if r['policy_melhorias'] else 'inactive'}"
    acp["policy_config"] = acp.apply(label, axis=1)
    mun["policy_config"] = mun.apply(label, axis=1)

    # Capital = largest municipality by baseline window-mean population.
    cap_pop = br.groupby(["processing_acps", "mun_id"])["pop_base"].mean().reset_index()
    caps = (cap_pop.loc[cap_pop.groupby("processing_acps")["pop_base"].idxmax(),
                        ["processing_acps", "mun_id"]]
            .rename(columns={"mun_id": "capital_mun_id"}))
    mun = mun.merge(caps, on="processing_acps", how="left")
    mun["is_capital"] = mun["mun_id"] == mun["capital_mun_id"]

    cap = mun[mun["is_capital"]].copy()

    per = mun[~mun["is_capital"]].copy()
    for src, dst in [("delta_regional_gini", "w_g"),
                     ("delta_regional_house_values", "w_h"),
                     ("delta_median_affordability", "w_a")]:
        per[dst] = per[src] * per["pop_base"]
    gp = ["processing_acps", "policy_config", "interest_housing",
          "policy_melhorias", "seed"]
    pa = per.groupby(gp).agg(sg=("w_g", "sum"), sh=("w_h", "sum"), sa=("w_a", "sum"),
                             total_pop=("pop_base", "sum"),
                             n_municipalities=("mun_id", "nunique")).reset_index()
    pa["delta_gini_periphery"] = pa["sg"] / pa["total_pop"]
    pa["delta_house_values_periphery"] = pa["sh"] / pa["total_pop"]
    pa["delta_median_affordability_periphery"] = pa["sa"] / pa["total_pop"]
    per_out = pa.drop(columns=["sg", "sh", "sa"])
    return acp, cap, per_out, (T0, T)


def load_published_panels(cities=None):
    acp = pd.read_csv(PUB_DIR / "acp_deltas.csv")
    cap = pd.read_csv(PUB_DIR / "capital_deltas.csv")
    per = pd.read_csv(PUB_DIR / "periphery_deltas.csv")
    for f in (acp, cap, per):
        f["policy_melhorias"] = f["policy_melhorias"].astype(bool)
    if cities is not None:
        acp = acp[acp["processing_acps"].isin(cities)]
        cap = cap[cap["processing_acps"].isin(cities)]
        per = per[per["processing_acps"].isin(cities)]
    return acp.copy(), cap.copy(), per.copy()


# ---------------------------------------------------------------------------
# Eq. 3 and the estimand diagnostics
# ---------------------------------------------------------------------------
def eq3(df, outcome, mech, cov="HC3"):
    fit = smf.ols(f"{outcome} ~ {mech} + C(processing_acps)", data=df).fit(cov_type=cov)
    p = fit.pvalues[mech]
    return {"beta": fit.params[mech], "se": fit.bse[mech], "t": fit.tvalues[mech],
            "p": p, "stars": stars(p), "r2": fit.rsquared, "n": int(fit.nobs),
            "n_cities": df["processing_acps"].nunique()}


SPECS = {
    "ACP": ("delta_gini", "delta_house_price", "delta_affordability_median"),
    "Capital": ("delta_regional_gini", "delta_regional_house_values",
                "delta_median_affordability"),
    "Periphery": ("delta_gini_periphery", "delta_house_values_periphery",
                  "delta_median_affordability_periphery"),
}


def table3(panels, tag):
    """Every cell of the paper's Table 3 / regression_split, for one batch."""
    acp, cap, per = panels
    rows = []
    for level, df in [("ACP", acp), ("Capital", cap), ("Periphery", per)]:
        y, m_prim, m_sec = SPECS[level]
        subsets = [("all configs", df),
                   ("melhorias OFF", df[~df["policy_melhorias"]]),
                   ("melhorias ON", df[df["policy_melhorias"]])]
        for sname, sub in subsets:
            if len(sub) < 10:
                continue
            for mname, mech in [("primary (house price)", m_prim),
                                ("secondary (rent/income)", m_sec)]:
                r = eq3(sub, y, mech)
                r.update({"batch": tag, "level": level, "subset": sname,
                          "mechanism": mname})
                rows.append(r)
    return rows


def city_slopes(d, outcome, mech):
    rows = []
    for c, g in d.groupby("processing_acps"):
        if g[mech].std() < 1e-14:
            continue
        fit = smf.ols(f"{outcome} ~ {mech}", data=g).fit()
        x = g[mech]
        rows.append({"city": c, "beta": fit.params[mech], "p": fit.pvalues[mech],
                     "n": int(fit.nobs), "within_var": float(((x - x.mean()) ** 2).sum())})
    r = pd.DataFrame(rows)
    r["weight"] = r["within_var"] / r["within_var"].sum()
    r["contribution"] = r["beta"] * r["weight"]
    return r.sort_values("weight", ascending=False)


def mean_group(cs):
    b = cs["beta"].values
    mg, se = b.mean(), b.std(ddof=1) / np.sqrt(len(b))
    t = mg / se
    return {"mean_group": mg, "se": se, "t": t,
            "p": 2 * (1 - sps.t.cdf(abs(t), len(b) - 1)), "k_cities": len(b)}


def poolability(d, outcome, mech):
    r = smf.ols(f"{outcome} ~ {mech} + C(processing_acps)", data=d).fit()
    u = smf.ols(f"{outcome} ~ {mech}*C(processing_acps)", data=d).fit()
    dfn = u.df_model - r.df_model
    F = ((r.ssr - u.ssr) / dfn) / (u.ssr / u.df_resid)
    return {"F": F, "df_num": dfn, "df_den": u.df_resid,
            "p": 1 - sps.f.cdf(F, dfn, u.df_resid)}


def clustered(d, outcome, mech):
    fit = smf.ols(f"{outcome} ~ {mech} + C(processing_acps)", data=d).fit(
        cov_type="cluster", cov_kwds={"groups": d["processing_acps"]})
    return {"beta": fit.params[mech], "se": fit.bse[mech], "p": fit.pvalues[mech]}


# ---------------------------------------------------------------------------
# Levels
# ---------------------------------------------------------------------------
def validation_levels(df):
    d = compute_derived_monthly_indicators(df)
    d = d[(d["month"] >= EVAL_START) & (d["month"] <= EVAL_END)]
    per_run = d.groupby(["processing_acps", "run_id"])[INDICATORS].mean().reset_index()
    return per_run[INDICATORS].mean(), per_run.groupby("processing_acps")[INDICATORS].mean()


def paper_table2(df):
    d = compute_derived_monthly_indicators(df)
    d = d[(d["month"] >= EVAL_START) & (d["month"] <= EVAL_END)]
    pr = d.groupby("run_id")[list(PAPER_TABLE2)].mean()
    return pd.DataFrame({"median": pr.median(), "p10": pr.quantile(.1),
                         "p90": pr.quantile(.9)})


# ---------------------------------------------------------------------------
def main():
    print("=" * 90)
    print("TIER-2 COMPARISON: corrected model, 26 of 27 cities (SAO PAULO pending)")
    print("=" * 90)

    print("\n[0] Batch integrity")
    new = load_stats(NEW_STATS, "new")
    old = load_stats(OLD_STATS, "submitted")
    cities26 = sorted(new["processing_acps"].unique())
    old26 = old[old["processing_acps"].isin(cities26)].copy()
    for lab, d in [("new", new), ("submitted", old)]:
        cells = d.groupby(["processing_acps", "policy_melhorias",
                           "interest_housing"])["seed"].nunique()
        print(f"  [{lab}] sims={d['simulation_id'].nunique()} "
              f"cities={d['processing_acps'].nunique()} "
              f"seeds/cell={sorted(cells.unique())} "
              f"cells={len(cells)}")
    missing = sorted(set(old["processing_acps"].unique()) - set(cities26))
    print(f"  cities in submitted but not in new: {missing}")

    # matched-seed check: the three interest arms share historical rates pre-2020
    pre = new[new["month"] < "2020-01-01"]
    cols = ["gdp_level", "unemployment", "house_price", "house_vacancy",
            "gini_index", "pop"]
    worst = 0.0
    for _, g in pre.groupby(["processing_acps", "policy_melhorias", "seed"]):
        piv = g.pivot_table(index="month", columns="interest_housing", values=cols)
        for c in cols:
            s = piv[c]
            den = s.abs().max(axis=1).replace(0, np.nan)
            worst = max(worst, float(((s.max(axis=1) - s.min(axis=1)).abs() / den).max()))
    print(f"  [new] max pre-2020 relative spread across interest arms: {worst:.2e} -> "
          f"{'MATCHED' if worst < 1e-9 else 'NOT MATCHED'}")

    reg_new = load_regional(NEW_REG, "new")
    print(f"  [new] regional rows={len(reg_new):,} sims={reg_new['simulation_id'].nunique()} "
          f"munis={reg_new['mun_id'].nunique()}")

    # ---- 1. levels ------------------------------------------------------
    print(f"\n[1] Nine validation indicators, eval window {EVAL_START[:7]}..{EVAL_END[:7]}")
    p_new, city_new = validation_levels(new)
    p_old26, city_old = validation_levels(old26)
    p_old27, _ = validation_levels(old)
    lv = pd.DataFrame({"submitted27": p_old27, "submitted26": p_old26, "new26": p_new})
    lv["pct_chg_vs_sub26"] = 100 * (lv["new26"] - lv["submitted26"]) / lv["submitted26"].abs()
    lv["target"] = [f"{TARGETS[i][0]:g}-{TARGETS[i][1]:g}" for i in lv.index]
    v = lambda i, x: "PASS" if TARGETS[i][0] <= x <= TARGETS[i][1] else "FAIL"
    lv["v_sub27"] = [v(i, x) for i, x in lv["submitted27"].items()]
    lv["v_sub26"] = [v(i, x) for i, x in lv["submitted26"].items()]
    lv["v_new26"] = [v(i, x) for i, x in lv["new26"].items()]
    lv["verdict_change"] = np.where(lv["v_sub26"] == lv["v_new26"], "", "<-- CHANGED")
    print(lv.round(4).to_string())
    lv.to_csv(OUT_DIR / "density_tier2_levels.csv")

    per_city = (city_new - city_old) / city_old.abs() * 100
    print("\n  per-city % change vs submitted (same city):")
    print(per_city.round(1).to_string())
    per_city.to_csv(OUT_DIR / "density_tier2_levels_by_city.csv")

    print("\n[1b] Paper Table 2 (housing validation), published format")
    t_old27, t_old26, t_new = paper_table2(old), paper_table2(old26), paper_table2(new)
    fmt = lambda t, i: f"{t.loc[i,'median']:.3g} ({t.loc[i,'p10']:.3g}-{t.loc[i,'p90']:.3g})"
    inside = lambda x, i: PAPER_TABLE2[i][0] <= x <= PAPER_TABLE2[i][1]
    t2 = pd.DataFrame({
        "empirical": [f"{PAPER_TABLE2[i][0]:g}-{PAPER_TABLE2[i][1]:g}" for i in PAPER_TABLE2],
        "submitted27": [fmt(t_old27, i) for i in PAPER_TABLE2],
        "submitted26": [fmt(t_old26, i) for i in PAPER_TABLE2],
        "new26": [fmt(t_new, i) for i in PAPER_TABLE2],
        "pct_chg": [100 * (t_new.loc[i, "median"] - t_old26.loc[i, "median"])
                    / abs(t_old26.loc[i, "median"]) for i in PAPER_TABLE2],
        "dag_pub": ["" if inside(t_old27.loc[i, "median"], i) else "dag" for i in PAPER_TABLE2],
        "dag_new": ["" if inside(t_new.loc[i, "median"], i) else "dag" for i in PAPER_TABLE2],
    }, index=list(PAPER_TABLE2))
    t2["changed"] = np.where(t2.dag_pub != t2.dag_new, "<-- FLIP", "")
    print(t2.round(3).to_string())
    t2.to_csv(OUT_DIR / "density_tier2_paper_table2.csv")

    # ---- 2. delta panels -------------------------------------------------
    print("\n[2] Building delta panels (prepare_data.py logic) for the new batch")
    acp_n, cap_n, per_n, (t0, t1) = build_panels(new, reg_new)
    expect = 5 * new.groupby("processing_acps")["seed"].nunique().sum()
    print(f"  window {t0:%Y-%m}..{t1:%Y-%m}   acp={len(acp_n)} (expect {expect}) "
          f"cap={len(cap_n)} per={len(per_n)} rows; "
          f"periphery cities={per_n['processing_acps'].nunique()}")
    assert len(acp_n) == expect, "delta panel row count != cities x 5 configs x seeds"
    acp_p27, cap_p27, per_p27 = load_published_panels()
    acp_p26, cap_p26, per_p26 = load_published_panels(cities26)
    print(f"  published: acp27={len(acp_p27)} acp26={len(acp_p26)} "
          f"per27={len(per_p27)} per26={len(per_p26)}")
    acp_n.to_csv(OUT_DIR / "density_tier2_acp_deltas.csv", index=False)
    cap_n.to_csv(OUT_DIR / "density_tier2_capital_deltas.csv", index=False)
    per_n.to_csv(OUT_DIR / "density_tier2_periphery_deltas.csv", index=False)

    # ---- 3. Table 3 ------------------------------------------------------
    print("\n[3] Eq. 3 at three levels (OLS + city FE, HC3) -- the paper's Table 3")
    rows = []
    rows += table3((acp_p27, cap_p27, per_p27), "published n=3 (27 cities)")
    rows += table3((acp_p26, cap_p26, per_p26), "published n=3 (26 cities)")
    rows += table3((acp_n, cap_n, per_n), "new n=10 (26 cities)")
    sub3 = lambda d: d[d["seed"] < 3]
    rows += table3((sub3(acp_n), sub3(cap_n), sub3(per_n)), "new n=3 subsample (26)")
    reg = pd.DataFrame(rows)
    for mech in ["secondary (rent/income)", "primary (house price)"]:
        print(f"\n  === mechanism: {mech} ===")
        for sname in ["all configs", "melhorias OFF", "melhorias ON"]:
            s = reg[(reg["mechanism"] == mech) & (reg["subset"] == sname)]
            print(f"\n  -- {sname}")
            print(s[["level", "batch", "beta", "se", "t", "p", "stars", "r2", "n"]]
                  .to_string(index=False,
                             formatters={"beta": "{:+.4g}".format, "se": "{:.3g}".format,
                                         "t": "{:+.2f}".format, "p": "{:.3g}".format,
                                         "r2": "{:.3f}".format}))
    reg.to_csv(OUT_DIR / "density_tier2_regressions.csv", index=False)

    # ---- 4. slope heterogeneity -----------------------------------------
    print("\n[4] Is Eq. 3's common-slope restriction defensible? "
          "(secondary mechanism, ACP level)")
    slope_rows, het_rows = [], []
    for tag, d in [("published n=3 (27)", acp_p27), ("published n=3 (26)", acp_p26),
                   ("new n=10 (26)", acp_n)]:
        for arm, s in [("OFF", d[~d["policy_melhorias"]]), ("ON", d[d["policy_melhorias"]])]:
            y, _, mech = SPECS["ACP"]
            pooled = eq3(s, y, mech, cov="nonrobust")
            cl = clustered(s, y, mech)
            pool = poolability(s, y, mech)
            cs = city_slopes(s, y, mech)
            mg = mean_group(cs)
            print(f"\n  {tag} | melhorias {arm}")
            print(f"    pooled FE beta = {pooled['beta']:+.4f} (p={pooled['p']:.3g}"
                  f"{pooled['stars']}) | city-clustered p={cl['p']:.3g}")
            print(f"    mean-group     = {mg['mean_group']:+.4f} "
                  f"(se={mg['se']:.3f}, p={mg['p']:.3g}, k={mg['k_cities']})")
            print(f"    common-slope F({pool['df_num']:.0f},{pool['df_den']:.0f})="
                  f"{pool['F']:.2f} p={pool['p']:.3g} -> "
                  f"{'REJECTED' if pool['p'] < 0.05 else 'not rejected'}")
            top = cs.head(6)
            print(f"    top-6 FE weights: " + ", ".join(
                f"{r.city} b={r.beta:+.2f} w={r.weight:.2f}" for r in top.itertuples()))
            print(f"    weight concentration: top-3 = {cs['weight'].head(3).sum():.0%}, "
                  f"share of cities with beta>0 = {(cs['beta'] > 0).mean():.0%}")
            cs.insert(0, "arm", arm)
            cs.insert(0, "batch", tag)
            slope_rows.append(cs)
            het_rows.append({"batch": tag, "arm": arm, "pooled_fe": pooled["beta"],
                             "pooled_p": pooled["p"], "cluster_p": cl["p"],
                             "mean_group": mg["mean_group"], "mg_se": mg["se"],
                             "mg_p": mg["p"], "F": pool["F"], "F_p": pool["p"],
                             "k_cities": mg["k_cities"],
                             "top3_weight": cs["weight"].head(3).sum(),
                             "share_beta_pos": (cs["beta"] > 0).mean()})
    pd.concat(slope_rows).to_csv(OUT_DIR / "density_tier2_city_slopes.csv", index=False)

    # ---- 4b. did the coefficients actually move? -------------------------
    # Two independent estimates (no matched seeds exist -- defect #6), so a
    # Wald z on the difference is the available test.
    def zdiff(a, b):
        d = a["beta"] - b["beta"]
        se = np.hypot(a["se"], b["se"])
        z = d / se
        return d, se, z, 2 * (1 - sps.norm.cdf(abs(z)))

    print("\n[4b] Wald z-tests: (i) published vs corrected, (ii) the paper's own "
          "1.16-vs-0.66 lever comparison, within each batch")
    cmp_rows = []
    for level in ["ACP", "Capital", "Periphery"]:
        for mech in ["secondary (rent/income)", "primary (house price)"]:
            for sname in ["melhorias OFF", "melhorias ON", "all configs"]:
                sel = lambda b: reg[(reg.level == level) & (reg.mechanism == mech)
                                    & (reg.subset == sname) & (reg.batch == b)]
                a, b = sel("published n=3 (26 cities)"), sel("new n=10 (26 cities)")
                if a.empty or b.empty:
                    continue
                d, se, z, p = zdiff(a.iloc[0], b.iloc[0])
                cmp_rows.append({"test": "published26 vs new26", "level": level,
                                 "mechanism": mech, "subset": sname,
                                 "beta_pub": a.iloc[0]["beta"], "beta_new": b.iloc[0]["beta"],
                                 "diff": d, "z": z, "p": p})
    for batch in ["published n=3 (26 cities)", "new n=10 (26 cities)"]:
        for level in ["ACP", "Capital", "Periphery"]:
            sel = lambda s: reg[(reg.level == level)
                                & (reg.mechanism == "secondary (rent/income)")
                                & (reg.subset == s) & (reg.batch == batch)]
            off, on = sel("melhorias OFF"), sel("melhorias ON")
            if off.empty or on.empty:
                continue
            d, se, z, p = zdiff(off.iloc[0], on.iloc[0])
            cmp_rows.append({"test": f"OFF vs ON within {batch}", "level": level,
                             "mechanism": "secondary (rent/income)", "subset": "OFF - ON",
                             "beta_pub": off.iloc[0]["beta"], "beta_new": on.iloc[0]["beta"],
                             "diff": d, "z": z, "p": p})
    cmpdf = pd.DataFrame(cmp_rows)
    print(cmpdf.to_string(index=False, formatters={
        "beta_pub": "{:+.4g}".format, "beta_new": "{:+.4g}".format,
        "diff": "{:+.4g}".format, "z": "{:+.2f}".format, "p": "{:.3g}".format}))
    cmpdf.to_csv(OUT_DIR / "density_tier2_coef_tests.csv", index=False)
    het = pd.DataFrame(het_rows)
    print("\n  summary")
    print(het.to_string(index=False, float_format=lambda x: f"{x:.4g}"))
    het.to_csv(OUT_DIR / "density_tier2_heterogeneity.csv", index=False)

    # ---- 5. delta magnitudes by config ----------------------------------
    print("\n[5] Delta magnitudes by configuration (ACP level, mean +/- sd over cities x seeds)")
    for tag, d in [("published n=3 (26)", acp_p26), ("new n=10 (26)", acp_n)]:
        g = (d.groupby("policy_config")[["delta_gini", "delta_affordability_median",
                                         "delta_house_price", "delta_house_quality"]]
               .agg(["mean", "std"]))
        print(f"\n  {tag}")
        print(g.round(6).to_string())

    # ---- 6. capital vs periphery ----------------------------------------
    print("\n[6] Capital vs periphery gap (periphery - capital), the paper's Section 3.5")
    gaps = []
    for tag, cp, pp in [("published n=3 (26)", cap_p26, per_p26),
                        ("new n=10 (26)", cap_n, per_n)]:
        c = cp[["processing_acps", "policy_config", "seed", "delta_regional_gini",
                "delta_regional_house_values", "delta_median_affordability"]]
        p = pp[["processing_acps", "policy_config", "seed", "delta_gini_periphery",
                "delta_house_values_periphery", "delta_median_affordability_periphery"]]
        pr = c.merge(p, on=["processing_acps", "policy_config", "seed"], how="inner")
        pr["gap_gini"] = pr["delta_gini_periphery"] - pr["delta_regional_gini"]
        pr["gap_rent"] = (pr["delta_median_affordability_periphery"]
                          - pr["delta_median_affordability"])
        cty = pr.groupby("processing_acps")[["delta_regional_gini", "delta_gini_periphery",
                                             "gap_gini", "gap_rent"]].mean()
        n_worse = int((cty["gap_gini"] > 0).sum())
        t = sps.ttest_1samp(cty["gap_gini"], 0)
        print(f"\n  {tag}: periphery worse in {n_worse}/{len(cty)} cities; "
              f"mean gap={cty['gap_gini'].mean():+.6f} (paired t p={t.pvalue:.3g})")
        cty.insert(0, "batch", tag)
        gaps.append(cty)
    pd.concat(gaps).to_csv(OUT_DIR / "density_tier2_capital_periphery.csv")

    # ---- 7. melhorias take-up -------------------------------------------
    print("\n[7] Melhorias take-up, with the eligible base beside it "
          "(no melhorias number travels without its base)")
    on = reg_new[reg_new["policy_melhorias"]]
    # Eligible base at the moment the policy can first act, summed over the
    # ACP's municipalities; upgrades cumulated over the whole 30-year horizon.
    start = on["month"].min()
    base = (on[on["month"] == start].groupby(["processing_acps", "simulation_id"])
              .agg(eligible0=("melhorias_eligible", "sum"), pop0=("pop", "sum"))
              .reset_index().groupby("processing_acps")[["eligible0", "pop0"]].mean())
    tot = (on.groupby(["processing_acps", "simulation_id"])["melhorias_upgrades"].sum()
             .reset_index().groupby("processing_acps")["melhorias_upgrades"]
             .agg(["mean", "std"]))
    tk = base.join(tot.rename(columns={"mean": "upgrades_total",
                                       "std": "upgrades_sd"}))
    tk["eligible0_per_1000"] = 1000 * tk["eligible0"] / tk["pop0"]
    # 30-year flow of upgrades against the t=0 eligible stock, so ratios above
    # 100% are expected: the eligible stock replenishes as houses degrade and
    # new families form.
    tk["upgrades_per_base0"] = tk["upgrades_total"] / tk["eligible0"].replace(0, np.nan)
    tk = tk.sort_values("eligible0_per_1000", ascending=False)
    print(tk[["eligible0", "pop0", "eligible0_per_1000", "upgrades_total",
              "upgrades_sd", "upgrades_per_base0"]]
          .to_string(float_format=lambda x: f"{x:.2f}"))
    print(f"  cities where melhorias never fires: "
          f"{sorted(tk.index[tk['upgrades_total'] == 0])}")
    tk.to_csv(OUT_DIR / "density_tier2_melhorias_takeup.csv")

    # ---- 8. cross-city ordering resolvability ---------------------------
    print("\n[8] Is the per-city ordering resolvable at n=10? "
          "(mean delta_gini per city, +/- sem across configs x seeds)")
    ord_rows = []
    for tag, d in [("published n=3 (26)", acp_p26), ("new n=10 (26)", acp_n)]:
        g = d.groupby("processing_acps")["delta_gini"].agg(["mean", "sem", "count"])
        g["t"] = g["mean"] / g["sem"]
        g["sig05"] = g["t"].abs() > 1.96
        print(f"\n  {tag}: {int(g['sig05'].sum())}/{len(g)} cities with "
              f"|t|>1.96 on mean delta_gini")
        g.insert(0, "batch", tag)
        ord_rows.append(g)
    ordf = pd.concat(ord_rows)
    ordf.to_csv(OUT_DIR / "density_tier2_city_ordering.csv")
    piv = ordf.reset_index().pivot(index="processing_acps", columns="batch", values="mean")
    if piv.shape[1] == 2:
        rho = piv.corr(method="spearman").iloc[0, 1]
        pr = piv.corr().iloc[0, 1]
        print(f"\n  rank correlation of per-city mean delta_gini, published vs new: "
              f"spearman={rho:+.3f}  pearson={pr:+.3f}")
        print(piv.sort_values(piv.columns[0]).round(6).to_string())

    print(f"\nWrote density_tier2_*.csv to {OUT_DIR}")


if __name__ == "__main__":
    main()